# Import any required modules (none needed for now)
"""team_asparagine_script

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nHr0-gwEebrjsLU0SmFD9ydqAbFW8KoP
"""

# -----------------------------------------------
# CLASS DEFINITION
# -----------------------------------------------
class TeamAsparagine:
    """
    A class to represent the Team Asparagine.
    This class helps display team member details like name, country, hobby, etc.
    """

    def __init__(self, members):
        """
        Initialize the TeamAsparagine object.
        
        Parameters:
        members (dict): A dictionary containing all team members' information.
        """
        self.members = members

    # ----------------------------------------------------
    # METHODS TO DISPLAY DIFFERENT ATTRIBUTES
    # ----------------------------------------------------
    
    def show_members(self):
        """Display all team member names."""
        print("👥 Team Members:")
        for member in self.members.keys():
            print(f"- {member}")
        print()  # Add a blank line for readability

    def show_usernames(self):
        """Display Slack usernames for each team member."""
        print("💬 Slack Usernames:")
        for member, info in self.members.items():
            print(f"{member}: {info['Slack Username']}")
        print()

    def show_countries(self):
        """Display countries of each team member."""
        print("🌍 Countries:")
        for member, info in self.members.items():
            print(f"{member}: {info['Country']}")
        print()

    def show_hobbies(self):
        """Display hobbies of each team member."""
        print("🎨 Hobbies:")
        for member, info in self.members.items():
            print(f"{member}: {info['Hobby']}")
        print()

    def show_affiliations(self):
        """Display academic or research affiliations of each member."""
        print("🏫 Affiliations:")
        for member, info in self.members.items():
            print(f"{member}: {info['Affiliation']}")
        print()

    def show_fav_sequences(self):
        """Display the favorite DNA sequence for each team member."""
        print("🧬 Favourite DNA Sequences:")
        for member, info in self.members.items():
            print(f"{member}: {info['DNA Sequence of Favourite Gene']}")
        print()


# -----------------------------------------------
# TEAM DATA (Dictionary)
# -----------------------------------------------
member_team_asparagine = {
    "Ayşenur Akcan": {
        "Slack Username": "@Ayşenur Akcan",
        "Country": "Türkiye",
        "Hobby": "Mending something",
        "Affiliation": "Istanbul Technical University",
        "DNA Sequence of Favourite Gene": "TP3- ATGGAGGAGCCGCAGTCAGATCCTAGCGTCGAGCCCCCTCTGAGTCAGGAAACATTTTCAGACCTATGGAAACTACTTCCTGAAAACAACGTTCT"
    },
    "Oni David Sunday": {
        "Slack Username": "@Sunday",
        "Country": "Nigeria",
        "Hobby": "Reading",
        "Affiliation": "Wageningen University and Research",
        "DNA Sequence of Favourite Gene": "AKT1 - TCTTCTCCCACTCCCCAGCAAAGTCCCCCTTTTGTGAGTGTAGCTGCCAGTACCTAGGTGAATGGTTGACTCCCCTCGGAGCCTTCCT..."
    },
    "Noor Ul Ain Amir": {
        "Slack Username": "@Noor Ul Ain Amir",
        "Country": "Pakistan",
        "Hobby": "Baking",
        "Affiliation": "Forman Christian College, University",
        "DNA Sequence of Favourite Gene": "SHH - ACAAGCTCTCCAGGCTTGCTACCATTTAAAATCAGACTCTTTTTGTCTTTTGATTGCTGTCTCGCGACCCAACTCCGATGTGTTCCGTTATCAGCGGCCGGCAGCCTGCCATTCCAGCCCCT..."
    },
    "Ozlem Kalkan": {
        "Slack Username": "@anyavala...",
        "Country": "Ukraine- Turkey",
        "Hobby": "doing sport",
        "Affiliation": "Bonn University",
        "DNA Sequence of Favourite Gene": "8OHY - ATGGCTCAAAGCACTGTTTTGCCTATGCACTGTTTATACGGGATATTCCTCGAAGGCAACCTAAAGATTCAAAAGAATGATCAGGAAGGACTAAAGAAGTTTAAAGATAATATCAAAAAATT…"
    },
    "Daria Kriuchkova": {
        "Slack Username": "@Daria",
        "Country": "Ukraine",
        "Hobby": "Knitting",
        "Affiliation": "Kharkiv Polytechnic Institute",
        "DNA Sequence of Favourite Gene": "BRCA1 - ATGGAAGTTGTCATTTTGTGTTTCCAGGATTTATTTGCTCTTCGTGTCTTTGGGTAGCTGG…"
    },
    "Minenhle Mayisela": {
        "Slack Username": "@Minenhle Mayisela",
        "Country": "Eswatini and South Africa",
        "Hobby": "Reading",
        "Affiliation": "University of the Witwatersrand",
        "DNA Sequence of Favourite Gene": "LMNA - GACAAATTCCTTGACCCGAGGAGGATAGGGATGTGGCCTTCGGTCTTTCCTCGCAGCTCCGGGGCAAGCTAGGAGTGGGATGGAAGTCGAGGTCCCTAATTTTTTAAGGGGAGGGTGCGGGGAGAAGGGGTAGTATGCGGAAACAGAGCGGGTATGAAGCTGGCTAACGCCGCGCGCCCCCTCCCAGGACCCGCTCCTGCCCCGCGCCGG"
    },
    "Seventh Member": {
        "Slack Username": "@...",
        "Country": "...",
        "Hobby": "...",
        "Affiliation": "...",
        "DNA Sequence of Favourite Gene": "..."
    },
    "Eighth Member": {
        "Slack Username": "@...",
        "Country": "...",
        "Hobby": "...",
        "Affiliation": "...",
        "DNA Sequence of Favourite Gene": "..."
    }
}


# -----------------------------------------------
# MAIN EXECUTION (runs only if this file is executed directly)
# -----------------------------------------------
if __name__ == "__main__":
    # Create an instance of TeamAsparagine with our data
    team = TeamAsparagine(member_team_asparagine)
    
    # Display all team details using the class methods
    team.show_members()
    team.show_usernames()
    team.show_countries()
    team.show_hobbies()
    team.show_affiliations()
    team.show_fav_sequences()

# Note: To use this class in other files, simply import TeamAsparagine and member_team_asparagine
